.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LIBSWE 3 "August  10, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.mso www.tmac
.SH NAME
libswe \- Swiss Ephemeris
.SH SYNOPSIS
.B libswe
.RI "the Swiss Ephemeris"

.SH DESCRIPTION

The Swiss Ephemeris did not arise in the UNIX/Gnu Linux world and
hence does not have an  UNIX/Gnu Linux style manpage.
It is however
well documented in the following files in the package libswe-devel:
.HP 0
/usr/share/doc/libswe/swephprg.pdf 
.HP 0
/usr/share/doc/libswe/swisseph.pdf
.HP 0
/usr/share/doc/libswe/swephprg.html
.HP 0
/usr/share/doc/libswe/swisseph.html

This documentation can also be found on line on astrodienst's web pages.
.HP 0
.URL "http://www.astro.com/swisseph/swisseph.htm" "General Documentation"
.HP 0
.URL "http://www.astro.com/swisseph/swephprg.htm" "Programmer's Documentation"

.SH AUTHOR
The Swiss Ephemeris was written by Dieter Koch and Alois Treindl of Astrodienst.
.PP
This manual page was written by Paul Elliott <pelliott@blackpatchpanel.com>,
for the Debian project (and may be used by others).
